//declare https://docs.jboss.org/drools/release/5.2.0.Final/drools-expert-docs/html/ch05.html#d0e3390

package th.ug.rule
import java.util.Date;

declare Address
   number : int
   streetName : String
   city : String
end

declare Person
    name : String
    dateOfBirth : Date
    address : Address
end

rule "Using a rule unit with a declared type"
  when
    $p : Person( name == "Bob" )
  then   // Insert Mark, who is a customer of James.
    Address address = new Address();
    address.setCity("Shenzhen");
    address.setStreetName("Aiguo");
    $p.setAddress(address);
end
